mode     : selfcontained
framework: qb_minimal
github:
  user: kforner
  repo: kforner.github.io

# HIGHLIGHTER SETTINGS
highlighter: prettify
hitheme: twitter-bootstrap
prettify:
  linenums: true

# WIDGETS
#widgets: [disqus, mathjax, search]
widgets: [disqus, search]
#disqus:
#  shortname: kfornergithubio





