title: Karl's Blog

logo: assets/img/quartzbio_square_logo.png
#logo: assets/img/qb_horizontal_logo.jpg
background: assets/img/bgr-numerique.jpg
feed_img: assets/img/rss2.png

owner: Karl Forner
author:
  email: karl.forner@gmail.com
  github: kforner
  firstname: Karl
  lastname: Forner

#social:
#  github: ramnathv


# Choose url: / for local development
url: /
#url: http://kforner.github.io
# use e.g. for links on blogs source code (.Rmd)
rawurl: /
#rawurl: https://raw.github.com/ramnathv/poirotBlog/gh-pages/

navigation: 
  - {item: Home, href: index.html}
  - {item: About, href: about.html}

# google custom search engine
google_search_engine_id: 016732723349564622635:1pee01gdpao
google_analytics_id: UA-41262764-1
